<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'App Key' => '',
    'App Secret' => '',
    'Reset' => '重置',
    'Search' => '搜索',
    'Access Token' => '访问令牌',
    'Account' => '账户',
    'All Type' => '全部类型',
    'An unsupported grant type was requested' => '请求的授权类型不被支持',
    'An unsupported response type was requested.' => '请求的响应类型不被支持。',
    'App Domain' => 'App地址',
    'App Manage' => 'App 管理',
    'App Name' => '应用名称',
    'App Provider' => '主办单位名称',
    'Apps' => '应用列表',
    'Are you sure you want to delete this app?' => '你确定要删除该应用吗？',
    'Authorization Code' => '授权码',
    'Authorization code is missing.' => '缺少授权码。',
    'Batch Deletion' => '批量删除',
    'Client ID' => 'App Key',
    'Create' => '创建',
    'Create App' => '创建应用',
    'Create Client' => '创建App',
    'Created At' => '创建时间',
    'Delete' => '删除',
    'Delete Client' => '删除App',
    'Expires' => '过期',
    'Grant type' => '授权类型',
    'ICP Beian' => 'ICP备案',
    'Invalid login or password' => '账号或密码不正确',
    'Invalid or missing response type' => '无效的响应类型',
    'Invalid server state or the User Session has expired' => '会话已过期',
    'Invalid username or password' => '账号或密码不正确',
    'Login' => '登录',
    'Malformed auth header.' => '认证 Header 不正确。',
    'Manage Client' => 'App管理',
    'OAuth2IdentityInterface not implemented' => 'OAuth2IdentityInterface 未实现',
    'Only one method may be used to authenticate at a time (Auth header, POST or GET).' => '一次只能使用一种方法进行身份验证（Auth Header，POST或GET）。',
    'Operation' => '操作',
    'Password' => '密码',
    'Quick login' => '快速登录',
    'Redirect URI' => '网站回调域',
    'Redirect Uri' => '重定向URI',
    'Scope Authority' => 'Scope 权限',
    'Scopes' => 'Scope权限',
    'Show' => '查看',
    'Show App: ' => '查看应用',
    'Sign in with your {siteName} account' => '使用{siteName}账户登录',
    'Successful operation' => '操作成功',
    'The Refresh Token is invalid' => '刷新令牌无效',
    'The User denied access to your application' => '用户拒绝访问您的应用程序',
    'The access token provided has expired.' => '提供的访问令牌已过期。',
    'The access token provided is invalid.' => '提供的访问令牌无效。',
    'The access token was not found.' => '提供的访问令牌无效。',
    'The authorization code is not found or has been expired.' => '授权码未找到或已过期。',
    'The content type for POST requests must be "application/x-www-form-urlencoded"' => 'POST请求的内容类型必须是 "application/x-www-form-urlencoded"',
    'The grant type was not specified in the request' => '请求中未指定授权类型',
    'The redirect URI provided does not match' => '提供的重定向URI不匹配',
    'The request is missing "refresh_token" parameter' => '请求缺少 "refresh_token" 参数',
    'The requested page does not exist.' => '请求的页面不存在！',
    'Unable to create access token' => '无法创建访问令牌',
    'Unable to create authorization code' => '无法创建授权码',
    'Update' => '更新',
    'Update App: ' => '更新应用:',
    'Update Client' => 'App更新',
    'Updated At' => '更新时间',
    'User ID' => '用户ID',
    'User is not found.' => '该用户不存在。',
    'When putting the token in the body, the method must be POST.' => '将令牌放入正文时，该方法必须为POST。',
    'You are requesting with an invalid credential.' => '您正在请求无效的凭证。',
    'You need to confirm your email address.' => '您的账户需要激活电子邮件地址。',
    'Your account has been blocked.' => '您的帐户已被封锁。',
    'successfully deleted' => '删除成功',
];
