<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure? Deleted app can not be restored' => '',
    'Client ID' => '',
    'Client Secret' => '',
    'Error occurred while deleting app' => '',
    'Space-delimited list of approved scopes' => '',
    'Space-delimited list of grant types permitted, null = all' => '',
    'app has been deleted' => '',
    'app is not found' => '',
    'App Manage' => 'App 管理',
    'Apps' => '应用列表',
    'Are you sure you want to delete this app?' => '你确定要删除该应用吗？',
    'Create' => '创建',
    'Create App' => '创建应用',
    'Delete' => '删除',
    'Redirect URI' => '网站回调域',
    'Show' => '查看',
    'Show App: ' => '查看应用',
    'Successful operation' => '操作成功',
    'The requested page does not exist.' => '请求的页面不存在！',
    'Update' => '更新',
    'Update App: ' => '更新应用:',
    'User ID' => '用户ID',
    'successfully deleted' => '删除成功',
];
